---
- name: Configure sudoers directory.
  file:
    path: /etc/sudoers.d
    state: directory
    group: root
    owner: root
    mode: 0755

- name: Configure sudoers directory is scanned.
  become: yes
  lineinfile:
    regexp: '#includedir\s+/etc/sudoers.d'
    line: '#includedir /etc/sudoers.d'
    dest: /etc/sudoers

- name: Set default sudoers template
  set_fact:
    vagrant_sudoers_template: 'sudoers-{{ ansible_distribution }}.j2'

- name: Set sudoers template for Ubuntu and Vagrant version below 1.8.7
  set_fact:
    vagrant_sudoers_template: 'sudoers-{{ ansible_distribution }}-lt-1-8-7.j2'
  when: ansible_distribution == 'Ubuntu' and vagrant_version|version_compare('1.8.7', '<')

- name: Manage vagrant-syncedfolders sudoers file.
  template:
    dest: /etc/sudoers.d/vagrant-syncedfolders
    src: '{{ vagrant_sudoers_template }}'
    owner: root
    group: root
    mode: 0440
    force: yes
    validate: 'visudo -cf %s'
