---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define vagrant_package.
  set_fact:
    vagrant_package: "{{ __vagrant_package }}"
  when: vagrant_package is not defined

# Setup/install tasks.
- include: setup.yml
  static: no

# Configure Vagrant.
- include: configure.yml
  static: no
